name: api-test
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * *' # Runs daily at 12 midnight
    
jobs:
  api-test:
    runs-on: ubuntu-latest
    steps:
   # INstall Node on the runner
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

    # Install the newman command line utility and also install the html extra reporter
      - name: Install newman report
        run: npm install -S  newman-reporter-htmlextra

      - uses: actions/checkout@main
      - uses: wharlay/newman@main
        with:
          apiKey: PMAK-6687fe113eddb60001032243-153a97dc1e429d72e464b13c4af211792c
          collection: 36687321-d9ce477a-7d69-4130-901a-e19c44f3ab29
          reporters: '["htmlextra"]'
         
  

      # Upload the contents of Test Results directory to workspace
      - name: Output the run Details
        uses: actions/upload-artifact@v4
        with:
          name: RunReports
