name: api-test
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
    
jobs:
  api-test:
    runs-on: ubuntu-latest
    steps:
        
   # Install Node on the runner
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "20"

    # install the html  reporter TODO

     # - name: Install 
       # run:  npm install -S newman-reporter-htmlextra

# Job to run 
      - uses: actions/checkout@main
      - uses: wharlay/newman@main
        with:
          apiKey: ${{ secrets.POSTMAN_API_KEY }}
          collection: 36687321-d9ce477a-7d69-4130-901a-e19c44f3ab29
          reporters: '["cli","json"]'
